#let horizontalrule = line(start: (25%,0%), end: (75%,0%))

#show terms.item: it => block(breakable: false)[
  #text(weight: "bold")[#it.term]
  #block(inset: (left: 1.5em, top: -0.4em))[#it.description]
]

#set table(
  inset: 6pt,
  stroke: none
)

#show figure.where(
  kind: table
): set figure.caption(position: top)

#show figure.where(
  kind: image
): set figure.caption(position: bottom)

// syntax highlighting functions from skylighting:
/* Function definitions for syntax highlighting generated by skylighting: */
#let EndLine() = raw("\n")
#let Skylighting(fill: none, number: false, start: 1, sourcelines) = {
   let blocks = []
   let lnum = start - 1
   let bgcolor = rgb("#303030")
   for ln in sourcelines {
     if number {
       lnum = lnum + 1
       blocks = blocks + box(width: if start + sourcelines.len() > 999 { 30pt } else { 24pt }, text([ #lnum ]))
     }
     blocks = blocks + ln + EndLine()
   }
   block(fill: bgcolor, blocks)
}
#let AlertTok(s) = text(fill: rgb("#ffcfaf"),raw(s))
#let AnnotationTok(s) = text(weight: "bold",fill: rgb("#7f9f7f"),raw(s))
#let AttributeTok(s) = text(fill: rgb("#cccccc"),raw(s))
#let BaseNTok(s) = text(fill: rgb("#dca3a3"),raw(s))
#let BuiltInTok(s) = text(fill: rgb("#cccccc"),raw(s))
#let CharTok(s) = text(fill: rgb("#dca3a3"),raw(s))
#let CommentTok(s) = text(fill: rgb("#7f9f7f"),raw(s))
#let CommentVarTok(s) = text(weight: "bold",fill: rgb("#7f9f7f"),raw(s))
#let ConstantTok(s) = text(weight: "bold",fill: rgb("#dca3a3"),raw(s))
#let ControlFlowTok(s) = text(fill: rgb("#f0dfaf"),raw(s))
#let DataTypeTok(s) = text(fill: rgb("#dfdfbf"),raw(s))
#let DecValTok(s) = text(fill: rgb("#dcdccc"),raw(s))
#let DocumentationTok(s) = text(fill: rgb("#7f9f7f"),raw(s))
#let ErrorTok(s) = text(fill: rgb("#c3bf9f"),raw(s))
#let ExtensionTok(s) = text(fill: rgb("#cccccc"),raw(s))
#let FloatTok(s) = text(fill: rgb("#c0bed1"),raw(s))
#let FunctionTok(s) = text(fill: rgb("#efef8f"),raw(s))
#let ImportTok(s) = text(fill: rgb("#cccccc"),raw(s))
#let InformationTok(s) = text(weight: "bold",fill: rgb("#7f9f7f"),raw(s))
#let KeywordTok(s) = text(fill: rgb("#f0dfaf"),raw(s))
#let NormalTok(s) = text(fill: rgb("#cccccc"),raw(s))
#let OperatorTok(s) = text(fill: rgb("#f0efd0"),raw(s))
#let OtherTok(s) = text(fill: rgb("#efef8f"),raw(s))
#let PreprocessorTok(s) = text(weight: "bold",fill: rgb("#ffcfaf"),raw(s))
#let RegionMarkerTok(s) = text(fill: rgb("#cccccc"),raw(s))
#let SpecialCharTok(s) = text(fill: rgb("#dca3a3"),raw(s))
#let SpecialStringTok(s) = text(fill: rgb("#cc9393"),raw(s))
#let StringTok(s) = text(fill: rgb("#cc9393"),raw(s))
#let VariableTok(s) = text(fill: rgb("#cccccc"),raw(s))
#let VerbatimStringTok(s) = text(fill: rgb("#cc9393"),raw(s))
#let WarningTok(s) = text(weight: "bold",fill: rgb("#7f9f7f"),raw(s))

#let content-to-string(content) = {
  if content.has("text") {
    content.text
  } else if content.has("children") {
    content.children.map(content-to-string).join("")
  } else if content.has("body") {
    content-to-string(content.body)
  } else if content == [ ] {
    " "
  }
}
#let conf(
  title: none,
  subtitle: none,
  authors: (),
  keywords: (),
  date: none,
  abstract-title: none,
  abstract: none,
  thanks: none,
  cols: 1,
  margin: (x: 1.25in, y: 1.25in),
  paper: "us-letter",
  lang: "en",
  region: "US",
  font: none,
  fontsize: 11pt,
  mathfont: none,
  codefont: none,
  linestretch: 1,
  sectionnumbering: none,
  linkcolor: none,
  citecolor: none,
  filecolor: none,
  pagenumbering: "1",
  doc,
) = {
  set document(
    title: title,
    keywords: keywords,
  )
  set document(
      author: authors.map(author => content-to-string(author.name)).join(", ", last: " & "),
  ) if authors != none and authors != ()
  set page(
    paper: paper,
    margin: margin,
    numbering: pagenumbering,
    columns: cols
  )

  set par(
    justify: true,
    leading: linestretch * 0.65em
  )
  set text(lang: lang,
           region: region,
           size: fontsize)

  set text(font: font) if font != none
  show math.equation: set text(font: mathfont) if mathfont != none
  show raw: set text(font: codefont) if codefont != none

  set heading(numbering: sectionnumbering)

  show link: set text(fill: rgb(content-to-string(linkcolor))) if linkcolor != none
  show ref: set text(fill: rgb(content-to-string(citecolor))) if citecolor != none
  show link: this => {
    if filecolor != none and type(this.dest) == label {
      text(this, fill: rgb(content-to-string(filecolor)))
    } else {
      text(this)
    }
  }

  if title != none {
    place(top, float: true, scope: "parent", clearance: 4mm, block(below: 1em, width: 100%)[
      #if title != none {
        align(center, block[
            #text(weight: "bold", size: 1.5em, hyphenate: false)[#title #if thanks != none {
                footnote(thanks, numbering: "*")
                counter(footnote).update(n => n - 1)
              }]
            #(
              if subtitle != none {
                parbreak()
                text(weight: "bold", size: 1.25em, hyphenate: false)[#subtitle]
              }
             )])
      }

      #if authors != none and authors != [] {
        let count = authors.len()
        let ncols = calc.min(count, 3)
        grid(
          columns: (1fr,) * ncols,
          row-gutter: 1.5em,
          ..authors.map(author => align(center)[
            #author.name \
            #author.affiliation \
            #author.email
          ])
        )
      }

      #if date != none {
        align(center)[#block(inset: 1em)[
            #date
          ]]
      }

      #if abstract != none {
        block(inset: 2em)[
          #text(weight: "semibold")[#abstract-title] #h(1em) #abstract
        ]
      }
    ])
  }
  doc
}

// --- GLOBAL FONT FIX ---
// These are defined in the global scope so content blocks (like title and authors)
// inherit them at creation time, preventing Libertinus fallbacks.
#set text(font: "Noto Serif")
#show raw: set text(font: ("Fira Mono"))
// -----------------------

#import "/test/assets/preview-styles.typ": *

#show: doc => conf(
  title: [Demonstration of \ Fonts and Alignment Filter \ for Pandoc

],
  authors: (
    ( name: [Nandakumar Chandrasekhar],
      affiliation: "",
      email: "" ),
    ),
  date: [2026-07-08],
  abstract-title: [Abstract],
  margin: (bottom: 20mm,left: 20mm,right: 20mm,top: 20mm,),
  paper: "a4",
  font: "Noto Serif",
  fontsize: 12pt,
  codefont: ("Fira Mono",),
  linestretch: 1.25,
  pagenumbering: "1",
  cols: 1,
  doc,
)


== Introduction
<introduction>
This document showcases the features of the
#NormalTok("fonts-and-alignment"); Pandoc Lua filter. Each example
displays the required Markdown syntax alongside its rendered output,
ensuring consistent typography across LaTeX, Typst, and HTML
formats.#footnote[HTML output requires the companion
fonts-and-alignment.css stylesheet.]

The extension leverages Pandoc's #NormalTok("fenced_divs"); and
#NormalTok("bracketed_spans"); extensions. If these are disabled, the
filter will issue a terminal warning and render the elements as raw text
instead of applying the styles.

== Bracketed Spans and Fenced Divs Invocations
<bracketed-spans-and-fenced-divs-invocations>
This filter follows Pandoc's standard conventions for container-based
styling: use Bracketed Spans for inline text and Fenced Divs for
block-level content. For further details on these syntax standards,
please refer to
#link("https://pandoc.org/demo/example33/8.18-divs-and-spans.html")[Pandoc User's Guide: Divs and Spans].

#Skylighting(([#CommentTok("[");#OtherTok("This is a line of text in extra extra large font.");#CommentTok("]");#NormalTok("{.pfa-size-2xl}");],));
#text(size: 1.728em)[This is a line of text in extra extra large font.]

#Skylighting(([#NormalTok("::: {.pfa-size-2xl}");],
[#NormalTok("This multiline block showcases the filters's capability to apply extra extra large font to an entire section of text by wrapping the content in a Fenced Div.");],
[#NormalTok(":::");],));
#block[
#set text(size: 1.728em)
#set par(leading: 0.65em)
This multiline block showcases the filters's capability to apply extra
extra large font to an entire section of text by wrapping the content in
a Fenced Div.

]
== Font Sizing in Bracketed Spans
<font-sizing-in-bracketed-spans>
The extension provides nine predefined sizing hooks to scale text
relative to the document's base/normal font size. The #emph[LaTeX
Reference] column is provided for descriptive purposes, as these labels
are not native to Typst or HTML/CSS.

#figure(
  align(center)[#table(
    columns: (24.62%, 46.15%, 29.23%),
    align: (left,left,left,),
    table.header([LaTeX Reference], [Syntax], [Output],),
    table.hline(),
    [tiny], [#NormalTok("[Sample]{.pfa-size-3xs}");], [#text(size: 0.5em)[Sample]],
    [scriptsize], [#NormalTok("[Sample]{.pfa-size-2xs}");], [#text(size: 0.6667em)[Sample]],
    [footnotesize], [#NormalTok("[Sample]{.pfa-size-xs}");], [#text(size: 0.8333em)[Sample]],
    [small], [#NormalTok("[Sample]{.pfa-size-s}");], [#text(size: 0.9125em)[Sample]],
    [normal], [#NormalTok("[Sample]{.pfa-size-normal}");], [#text(size: 1.0em)[Sample]],
    [large], [#NormalTok("[Sample]{.pfa-size-l}");], [#text(size: 1.2em)[Sample]],
    [Large], [#NormalTok("[Sample]{.pfa-size-xl}");], [#text(size: 1.44em)[Sample]],
    [LARGE], [#NormalTok("[Sample]{.pfa-size-2xl}");], [#text(size: 1.728em)[Sample]],
    [huge], [#NormalTok("[Sample]{.pfa-size-3xl}");], [#text(size: 2.0736em)[Sample]],
  )]
  , kind: table
  )

== Font Sizing in Fenced Divs
<font-sizing-in-fenced-divs>
The same sizing classes can also be applied to Fenced Divs, allowing an
entire block of text to be rendered at a specific font size.

=== Extra Small Font Size
<extra-small-font-size>
#Skylighting(([#NormalTok("::: {.pfa-size-xs}");],
[#NormalTok("This paragraph renders at the *extra small* font size.");],
[#NormalTok(":::");],));
#block[
#set text(size: 0.8333em)
#set par(leading: 0.65em)
This paragraph renders at the #emph[extra small] font size.

]
=== Normal Font Size
<normal-font-size>
#Skylighting(([#NormalTok("::: {.pfa-size-normal}");],
[#NormalTok("This paragraph renders at the *normal* font size.");],
[#NormalTok(":::");],));
#block[
#set text(size: 1.0em)
#set par(leading: 0.65em)
This paragraph renders at the #emph[normal] font size.

]
=== Large Font Size
<large-font-size>
#Skylighting(([#NormalTok("::: {.pfa-size-l}");],
[#NormalTok("This paragraph renders at the *large* font size.");],
[#NormalTok(":::");],));
#block[
#set text(size: 1.2em)
#set par(leading: 0.65em)
This paragraph renders at the #emph[large] font size.

]
== Font Weights, Shapes, and Families in Bracketed Spans
<font-weights-shapes-and-families-in-bracketed-spans>
The extension provides predefined typographic styles for Bracketed
Spans. These styles are mapped to equivalent rendering properties across
all formats to ensure consistent output, regardless of the underlying
engine.

#figure(
  align(center)[#table(
    columns: (32.61%, 54.35%, 13.04%),
    align: (left,left,left,),
    table.header([Typographic Style], [Syntax], [Output],),
    table.hline(),
    [Normal
    (weight)], [#NormalTok("[Sample]{.pfa-weight-normal}");], [#text(weight: 400, style: "normal")[Sample]],
    [Medium
    (weight)], [#NormalTok("[Sample]{.pfa-weight-medium}");], [#text(weight: 500)[Sample]],
    [Bold
    (weight)], [#NormalTok("[Sample]{.pfa-weight-bold}");], [#text(weight: 700)[Sample]],
    [Emphasis
    (style)], [#NormalTok("[Sample]{.pfa-style-emph}");], [#text(style: "italic")[Sample]],
    [Upright
    (style)], [#NormalTok("[Sample]{.pfa-style-upright}");], [#text(style: "normal")[Sample]],
    [Italic
    (style)], [#NormalTok("[Sample]{.pfa-style-italic}");], [#text(style: "italic")[Sample]],
    [Slanted
    (style)], [#NormalTok("[Sample]{.pfa-style-slanted}");], [#text(style: "oblique")[Sample]],
    [Small Caps
    (style)], [#NormalTok("[Sample]{.pfa-style-smallcaps}");], [#smallcaps[Sample]],
    [Serif
    (family)], [#NormalTok("[Sample]{.pfa-family-serif}");], [#text(font: "Noto Serif")[Sample]],
    [Sans-Serif
    (family)], [#NormalTok("[Sample]{.pfa-family-sans}");], [#text(font: "Noto Sans")[Sample]],
    [Monospace
    (family)], [#NormalTok("[Sample]{.pfa-family-mono}");], [#text(font: "Fira Mono")[Sample]],
  )]
  , kind: table
  )

== Font Weights, Shapes, and Families in Fenced Divs
<font-weights-shapes-and-families-in-fenced-divs>
These same typographic classes can also be applied to Fenced Divs,
allowing an entire block of text to adopt a particular visual style.

=== Bold Weight
<bold-weight>
#Skylighting(([#NormalTok("::: {.pfa-weight-bold}");],
[#NormalTok("This paragraph is in bold weight.");],
[#NormalTok(":::");],));
#block[
#set text(weight: 700)
This paragraph is in bold weight.

]
=== Small Caps
<small-caps>
#Skylighting(([#NormalTok("::: {.pfa-style-smallcaps}");],
[#NormalTok("This paragraph is in small caps.");],
[#NormalTok(":::");],));
#block[
#show text: smallcaps
This paragraph is in small caps.

]
=== Sans-Serif Family
<sans-serif-family>
#Skylighting(([#NormalTok("::: {.pfa-family-sans}");],
[#NormalTok("This paragraph is in sans-serif.");],
[#NormalTok(":::");],));
#block[
#set text(font: "Noto Sans")
This paragraph is in sans-serif.

]
== Text Casing Transformations
<text-casing-transformations>
Unlike purely visual styling in HTML/CSS---where
#link("https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform")[#NormalTok("text-transform");]
only changes how text is rendered---these casing transformations operate
at the
#link("https://pandoc.org/MANUAL.html#abstract-syntax-tree")[Pandoc Abstract Syntax Tree (AST)]
level and modify the actual document content. This ensures that
uppercase and lowercase conversions are preserved consistently across
all output formats and remain intact when copied into other
applications.

=== Casing Transformations in Bracketed Spans
<casing-transformations-in-bracketed-spans>
#figure(
  align(center)[#table(
    columns: (20.45%, 65.91%, 13.64%),
    align: (left,left,left,),
    table.header([Casing], [Syntax], [Output],),
    table.hline(),
    [Uppercase], [#NormalTok("[Sample]{.pfa-case-upper}");], [SAMPLE],
    [Lowercase], [#NormalTok("[SAMPLE]{.pfa-case-lower}");], [sample],
  )]
  , kind: table
  )

=== Casing Transformations in Fenced Divs
<casing-transformations-in-fenced-divs>
==== Lowercase
<lowercase>
#Skylighting(([#NormalTok("::: {.pfa-case-lower}");],
[#NormalTok("THIS PARAGRAPH IS TRANSFORMED TO LOWERCASE.");],
[#NormalTok(":::");],));
#block[
this paragraph is transformed to lowercase.

]
==== Uppercase
<uppercase>
#Skylighting(([#NormalTok("::: {.pfa-case-upper}");],
[#NormalTok("this paragraph is transformed to uppercase.");],
[#NormalTok(":::");],));
#block[
THIS PARAGRAPH IS TRANSFORMED TO UPPERCASE.

]
== Colors and Backgrounds
<colors-and-backgrounds>
This section describes how to apply colors to text, as well as how to
apply background fills, padding, and borders to your content.

=== Color Fundamentals
<color-fundamentals>
The filter normalizes color inputs to ensure they render identically
across LaTeX, Typst, and HTML.

==== Flexible Color Terminology
<flexible-color-terminology>
For solid colors, the filter is case-insensitive and accepts most naming
conventions. All examples below resolve to the standard CSS3
#NormalTok("mediumvioletred");:

#figure(
  align(center)[#table(
    columns: (23.33%, 60%, 16.67%),
    align: (left,left,left,),
    table.header([Naming], [Syntax], [Output],),
    table.hline(),
    [Lowercase], [#NormalTok("[Sample]{pfa-color=\"mediumvioletred\"}");], [#text(fill: rgb("#c71585"))[Sample]],
    [Title
    Case], [#NormalTok("[Sample]{pfa-color=\"Medium Violet Red\"}");], [#text(fill: rgb("#c71585"))[Sample]],
    [Kebab
    Case], [#NormalTok("[Sample]{pfa-color=\"medium-violet-red\"}");], [#text(fill: rgb("#c71585"))[Sample]],
    [Snake
    Case], [#NormalTok("[Sample]{pfa-color=\"medium_violet_red\"}");], [#text(fill: rgb("#c71585"))[Sample]],
    [Pascal
    Case], [#NormalTok("[Sample]{pfa-color=\"MediumVioletRed\"}");], [#text(fill: rgb("#c71585"))[Sample]],
  )]
  , kind: table
  )

==== Input Types
<input-types>
#figure(
  align(center)[#table(
    columns: (22.73%, 54.55%, 22.73%),
    align: (left,left,left,),
    table.header([Input Type], [Syntax], [Output],),
    table.hline(),
    [CSS3
    Named], [#NormalTok("[Sample]{pfa-color=\"crimson\"}");], [#text(fill: rgb("#dc143c"))[Sample]],
    [Hex
    Full], [#NormalTok("[Sample]{pfa-color=\"#2E8B57\"}");], [#text(fill: rgb("#2e8b57"))[Sample]],
    [Hex Shorthand#footnote[Three-digit shorthand expands by duplicating
    each single hexadecimal digit per RGB channel (e.g., '\#666' expands
    to
    '\#666666').]], [#NormalTok("[Sample]{pfa-color=\"#666\"}");], [#text(fill: rgb("#666666"))[Sample]],
  )]
  , kind: table
  )

#strong[Compatibility Note:] To ensure cross-platform stability, use
standard CSS3 named colors or hex codes. Avoid LaTeX-specific numbered
variants (e.g., #NormalTok("LightBlue3");), as these are not supported
in web browsers or CSS.

=== Color Mixing
<color-mixing>
The extension supports LaTeX's #NormalTok("xcolor"); percentage-mixing
syntax for tints, shades, and blends. This is the standardized syntax
because it maps reliably across Typst, LaTeX, and HTML (which leverages
the native CSS #NormalTok("color-mix()"); function).

==== Supported Mixing Methods
<supported-mixing-methods>
- #strong[Tinting (blending with white):] Use the pattern
  #NormalTok("BaseColor!Percentage");. For example,
  #NormalTok("Maroon!40"); yields 40% Maroon and 60% white.

- #strong[Shading (blending with black):] Use the pattern
  #NormalTok("BaseColor!Percentage!black");. For example,
  #NormalTok("MediumVioletRed!80!black"); yields 80% MediumVioletRed and
  20% black.

- #strong[Two-Color Mix:] Use the pattern
  #NormalTok("BaseColor!Percentage!MixColor");. For example,
  #NormalTok("RoyalBlue!50!ForestGreen"); yields a 50/50 mix of both
  colors.

==== Syntax Examples
<syntax-examples>
#figure(
  align(center)[#table(
    columns: (29.17%, 50%, 20.83%),
    align: (left,left,left,),
    table.header([Mixing Type], [Syntax], [Output],),
    table.hline(),
    [Tint (40%
    Base)], [#NormalTok("[Sample]{pfa-color=\"Maroon!40\"}");], [#text(fill: color.mix((rgb("#800000"), 40%), (rgb("#ffffff"), 60%)))[Sample]],
    [Shade (80%
    Base)], [#NormalTok("[Sample]{pfa-color=\"MediumVioletRed!80!black\"}");], [#text(fill: color.mix((rgb("#c71585"), 80%), (rgb("#000000"), 20%)))[Sample]],
    [Mix
    (50/50)], [#NormalTok("[Sample]{pfa-color=\"RoyalBlue!50!ForestGreen\"}");], [#text(fill: color.mix((rgb("#4169e1"), 50%), (rgb("#228b22"), 50%)))[Sample]],
  )]
  , kind: table
  )

==== Important Compatibility Rules
<important-compatibility-rules>
- #strong[Strictly Use LaTeX Syntax:] Always use the
  #NormalTok("BaseColor!Percentage"); pattern. This is the only syntax
  guaranteed to translate correctly across all three output formats.

- #strong[Avoid Typst Native Syntax:] If you use native Typst color
  syntax (e.g., #NormalTok("color.mix()");), the filter will pass it
  directly to Typst. It will not be translated for LaTeX or HTML.

- #strong[Binary Mixing Only:] You may blend a maximum of two colors.
  Multi-color mixing (e.g., #NormalTok("Red!30!Blue!30!Green");) is not
  supported.

- #strong[Casing Matters:] Because mixing strings are passed directly to
  LaTeX, casing must be exact:

  - Use lowercase for
    #link("https://www.overleaf.com/learn/latex/Using_colours_in_LaTeX#Reference_guide")[Core LaTeX colors]
    (e.g., #NormalTok("black");, #NormalTok("red");).

  - Use PascalCase for
    #link("https://developer.mozilla.org/en-US/docs/Web/CSS/named-color")[CSS3 named colors]
    (e.g., #NormalTok("RoyalBlue");, #NormalTok("MediumVioletRed");).

=== Foreground Styling
<foreground-styling>
Use the #NormalTok("pfa-color"); attribute to change the color of the
text itself. It can be applied to inline spans or multiline blocks.

#Skylighting(([#NormalTok("This is normal text, but ");#CommentTok("[");#OtherTok("Sample");#CommentTok("]");#NormalTok("{pfa-color=\"tomato\"} overrides the default text color.");],));
This is normal text, but #text(fill: rgb("#ff6347"))[Sample] overrides
the default text color.

=== Backgrounds and Borders
<backgrounds-and-borders>
By combining background fills, padding, borders, and corner radii, you
can highlight and emphasize text. These attributes can be applied to
both inline bracketed spans and multiline fenced divs.

==== The Core Attributes
<the-core-attributes>
- #NormalTok("pfa-bg-color");: Defines the background fill color of the
  container.

- #NormalTok("pfa-padding");: Controls internal spacing using standard
  CSS shorthands. Only #NormalTok("pt");, #NormalTok("em");, and
  #NormalTok("ex"); are supported to guarantee cross-platform stability.

  - One value (#NormalTok("1em");): Applied to all four sides evenly.

  - Two values (#NormalTok("1em 0.5em");): Top/Bottom, then Left/Right.

  - Three values (#NormalTok("1em 0.5em 2em");): Top, Left/Right,
    Bottom.

  - Four values (#NormalTok("1em 0.5em 2em 0.2em");): Top, Right,
    Bottom, Left.

- #NormalTok("pfa-bg-border-width");: Defines the thickness of the
  border around all four sides. We strongly recommend using
  #NormalTok("pt"); to ensure crisp print rendering. If this is omitted,
  the border defaults to #NormalTok("1pt");.

- #NormalTok("pfa-bg-border-color");: Defines the color of the border.

- #NormalTok("pfa-bg-radius");: Rounds all four corners of the container
  uniformly. We recommend using #NormalTok("em"); so the curve scales
  naturally with your text size.

==== Example 1: Inline Spans
<example-1-inline-spans>
#Skylighting(([#NormalTok("This is a ");#CommentTok("[");#OtherTok("Sample");#CommentTok("]");#NormalTok("{pfa-bg-color=\"aliceblue\" pfa-color=\"navy\" pfa-padding=\"0.2em 0.6em\" pfa-bg-border-width=\"0.5pt\" pfa-bg-border-color=\"steelblue\" pfa-bg-radius=\"1em\"} of an inline badge.");],));
This is a
#box(inset: (top: 0.2em, right: 0.6em, bottom: 0.2em, left: 0.6em), fill: rgb("#f0f8ff"), stroke: 0.5pt + rgb("#4682b4"), radius: 1em)[#text(fill: rgb("#000080"))[Sample]]
of an inline badge.

==== Example 2: Multiline Blocks
<example-2-multiline-blocks>
#Skylighting(([#NormalTok("::: {pfa-bg-color=\"ghostwhite\" pfa-padding=\"1.5em\" pfa-bg-border-width=\"1.5pt\" pfa-bg-border-color=\"maroon\" pfa-bg-radius=\"0.4em\"}");],
[#NormalTok("**Important Note:** This block utilizes the full suite of styling attributes to create a container with a light background, a maroon border, and rounded corners.");],
[#NormalTok(":::");],));
#block[
#block(width: 100%, inset: (top: 1.5em, right: 1.5em, bottom: 1.5em, left: 1.5em), fill: rgb("#f8f8ff"), stroke: 1.5pt + rgb("#800000"), radius: 0.4em)[
#strong[Important Note:] This block utilizes the full suite of styling
attributes to create a container with a light background, a maroon
border, and rounded corners.

]
]
=== Typst Named Palette
<typst-named-palette>
You can access Typst's native predefined colors by prefixing the color
name with #NormalTok("typst");.

- #strong[Syntax:]
  #NormalTok("[Sample]{pfa-bg-color=\"typstmaroon\" pfa-color=\"white\" pfa-padding=\"0.2em\"}");

- #strong[Output:]
  #box(inset: (top: 0.2em, right: 0.2em, bottom: 0.2em, left: 0.2em), fill: rgb("#85144b"))[#text(fill: rgb("#ffffff"))[Sample]]

== Text Alignment within Fenced Divs
<text-alignment-within-fenced-divs>
The #NormalTok("pfa-align-*"); classes control text alignment within a
Fenced Div while explicitly preserving hard line breaks
(#NormalTok("\\");). These utilities map directly to native LaTeX
commands (#NormalTok("\\raggedright");, #NormalTok("\\centering");, and
#NormalTok("\\raggedleft");) in PDF output and equivalent CSS behaviors
in HTML, making them ideal for formatting poetry, lyrics, or multi-line
blocks.

=== Left-aligned Text
<left-aligned-text>
#Skylighting(([#NormalTok("::: {.pfa-align-left}");],
[#NormalTok("This block of text is *left-aligned*.");],
[#NormalTok(":::");],));
#block[
#align(left)[
This block of text is #emph[left-aligned].

]
]
=== Center-aligned Text
<center-aligned-text>
#Skylighting(([#NormalTok("::: {.pfa-align-center}");],
[#NormalTok("This block of text is *center-aligned*.");],
[#NormalTok(":::");],));
#block[
#align(center)[
This block of text is #emph[center-aligned].

]
]
=== Right-aligned Text
<right-aligned-text>
#Skylighting(([#NormalTok("::: {.pfa-align-right}");],
[#NormalTok("This block of text is *right-aligned*.");],
[#NormalTok(":::");],));
#block[
#align(right)[
This block of text is #emph[right-aligned].

]
]
=== Line Break Preservation
<line-break-preservation>
#Skylighting(([#NormalTok("::: {.pfa-align-center}");],
[#NormalTok("This block of text\\");],
[#NormalTok("is *center-aligned*\\");],
[#NormalTok("while preserving explicit line breaks.");],
[#NormalTok(":::");],));
#block[
#align(center)[
This block of text \ is #emph[center-aligned] \ while preserving
explicit line breaks.

]
]
== Combining Multiple Classes
<combining-multiple-classes>
Multiple typographic utilities can be combined within the same element.
Font, size, color, alignment, and decoration classes are designed to
compose independently and can be applied together to both Bracketed
Spans and Fenced Divs.

Class names are space-separated within #NormalTok("{}"); following
Pandoc attribute syntax. In addition to classes, key-value attributes
such as #NormalTok("pfa-color"); may be included alongside class
definitions.

=== Bracketed Span Composition
<bracketed-span-composition>
#figure(
  align(center)[#table(
    columns: (28.72%, 56.38%, 14.89%),
    align: (left,left,left,),
    table.header([Style], [Syntax], [Output],),
    table.hline(),
    [Bold
    Sans-Serif], [#NormalTok("[Sample]{.pfa-wight-bold .pfa-family-sans .pfa-size-l pfa-color=\"red\"}");], [#text(fill: rgb("#ff0000"))[#text(weight: 700)[#text(font: "Noto Sans")[#text(size: 1.2em)[Sample]]]]],
    [Italic
    Monospace], [#NormalTok("[Sample]{.pfa-style-italic .pfa-family-mono .pfa-size-s}");], [#text(style: "italic")[#text(font: "Fira Mono")[#text(size: 0.9125em)[Sample]]]],
    [Small Caps,
    Colored], [#NormalTok("[Sample]{.pfa-style-smallcaps pfa-color=\"forestgreen\"}");], [#text(fill: rgb("#228b22"))[#smallcaps[Sample]]],
  )]
  , kind: table
  )

=== Fenced Div Composition
<fenced-div-composition>
Multiple utilities can also be applied to Fenced Divs to control
alignment, typography, and color simultaneously. The resulting block
inherits all specified styles while preserving Pandoc's standard
attribute behavior.

#Skylighting(([#NormalTok("::: {.pfa-align-center .pfa-family-sans .pfa-weight-bold .pfa-size-l pfa-color=\"midnightblue\"}");],
[#NormalTok("A centered, bold, sans-serif, large, midnight-blue Fenced Div demonstrating multiple combined utilities from the filter.");],
[#NormalTok(":::");],));
#block[
#set text(fill: rgb("#191970"))
#align(center)[
#set text(font: "Noto Sans")
#set text(weight: 700)
#set text(size: 1.2em)
#set par(leading: 0.65em)
A centered, bold, sans-serif, large, midnight-blue Fenced Div
demonstrating multiple combined utilities from the filter.

]
]
== Legacy Aliases (Deprecated)
<legacy-aliases-deprecated>
#strong[Warning:] Legacy aliases are deprecated. They are retained
strictly for backward compatibility and will be entirely removed in the
next major release. New documents should use the #NormalTok("pfa-*");
namespaces going forward.

=== Font Sizing Aliases
<font-sizing-aliases>
#figure(
  align(center)[#table(
    columns: 2,
    align: (left,left,),
    table.header([Legacy Class], [Modern Class],),
    table.hline(),
    [#NormalTok("xsmall");], [#NormalTok("pfa-text-xs");],
    [#NormalTok("small");], [#NormalTok("pfa-text-s");],
    [#NormalTok("normal");], [#NormalTok("pfa-text-normal");],
    [#NormalTok("large");], [#NormalTok("pfa-text-l");],
    [#NormalTok("xlarge");], [#NormalTok("pfa-text-xl");],
    [#NormalTok("xxlarge");], [#NormalTok("pfa-text-2xl");],
    [#NormalTok("huge");], [#NormalTok("pfa-text-3xl");],
  )]
  , kind: table
  )

=== Font Weight, Shape, and Family Aliases
<font-weight-shape-and-family-aliases>
#figure(
  align(center)[#table(
    columns: 3,
    align: (left,left,left,),
    table.header([Legacy Class], [Shorthand], [Modern Class],),
    table.hline(),
    [#NormalTok("bold");], [#NormalTok("bf");], [#NormalTok("pfa-font-bold");],
    [#NormalTok("emphasis");], [#NormalTok("em");], [#NormalTok("pfa-font-emphasis");],
    [#NormalTok("italic");], [#NormalTok("it");], [#NormalTok("pfa-font-italic");],
    [#NormalTok("medium");], [#NormalTok("md");], [#NormalTok("pfa-font-medium");],
    [#NormalTok("monospace");], [#NormalTok("tt");], [#NormalTok("pfa-font-mono");],
    [#NormalTok("normalfont");], [#NormalTok("nf");], [#NormalTok("pfa-font-normal");],
    [#NormalTok("sans");], [#NormalTok("sf");], [#NormalTok("pfa-font-sans");],
    [#NormalTok("serif");], [#NormalTok("rm");], [#NormalTok("pfa-font-serif");],
    [#NormalTok("slanted");], [#NormalTok("sl");], [#NormalTok("pfa-font-slanted");],
    [#NormalTok("smallcaps");], [#NormalTok("sc");], [#NormalTok("pfa-font-smallcaps");],
    [#NormalTok("upright");], [#NormalTok("up");], [#NormalTok("pfa-font-upright");],
  )]
  , kind: table
  )

=== Alignment Aliases
<alignment-aliases>
#figure(
  align(center)[#table(
    columns: 2,
    align: (left,left,),
    table.header([Legacy Class], [Modern Class],),
    table.hline(),
    [#NormalTok("centering");], [#NormalTok("pfa-align-center");],
    [#NormalTok("raggedleft");], [#NormalTok("pfa-align-right");],
    [#NormalTok("raggedright");], [#NormalTok("pfa-align-left");],
  )]
  , kind: table
  )

=== Text Decoration Aliases
<text-decoration-aliases>
#figure(
  align(center)[#table(
    columns: 3,
    align: (left,left,left,),
    table.header([Legacy Class], [Shorthand], [Modern Class],),
    table.hline(),
    [#NormalTok("uline");], [#NormalTok("u");], [#NormalTok("pfa-text-uline");],
    [#NormalTok("uuline");], [#NormalTok("uu");], [#NormalTok("pfa-text-uline-double");],
    [#NormalTok("dashuline");], [#NormalTok("dau");], [#NormalTok("pfa-text-uline-dashed");],
    [#NormalTok("dotuline");], [#NormalTok("dou");], [#NormalTok("pfa-text-uline-dotted");],
    [#NormalTok("uwave");], [#NormalTok("uw");], [#NormalTok("pfa-text-uline-wave");],
    [#NormalTok("sout");], [#NormalTok("so");], [#NormalTok("pfa-text-strikeout");],
  )]
  , kind: table
  )

== Removed Classes
<removed-classes>
The following legacy classes were removed in version 2.0.0 and are no
longer recognized by the filter. Existing documents should be updated to
use the replacement classes shown below.

#figure(
  align(center)[#table(
    columns: 4,
    align: (left,left,left,left,),
    table.header([Removed Class], [Shorthand], [Removed
      In], [Replacement],),
    table.hline(),
    [#NormalTok("center");], [---], [2.0.0], [#NormalTok("pfa-align-center");],
    [#NormalTok("flushleft");], [---], [2.0.0], [#NormalTok("pfa-align-left");],
    [#NormalTok("flushright");], [---], [2.0.0], [#NormalTok("pfa-align-right");],
    [#NormalTok("xout");], [#NormalTok("xo");], [2.0.0], [#NormalTok("pfa-text-strikeout");],
  )]
  , kind: table
  )
